---
title: "backup"
output: html_document
date: "2022-11-20"
---

---
title: "Class 11/17"
output: html_document
date: "2022-11-17"
---

```{r}
library(tidyverse)
library(dplyr)
library(usdata)
```

```{r}
rosters23_clean <- read_csv("https://raw.githubusercontent.com/dwillis/wbb-rosters/main/rosters_2022-23.csv")
```
#Things to fix
*Drop where name is NA
*Standardize positions
*Standardizing state
*Standardizing Year
*Standardizing Height

#Colums to add
*state
*country
*height in inches

```{r}
rosters23_clean <- rosters23_clean %>% mutate(hometown_clean = str_to_lower(hometown))

rosters23_clean <- rosters23_clean %>% separate(col=hometown_clean, into=c("new_hometown", "state"), sep=", ", extra="merge")
```

```{r}
rosters23_clean <- rosters23_clean %>% 
  mutate(state = str_trim(state), state = str_replace(state, '\\.','')) %>% 
  mutate(state = case_when(
     is.na(abbr2state(state)) ~ state,
     TRUE ~ abbr2state(state))
  )
```

```{r}
rosters23_clean <- rosters23_clean %>% 
  mutate(clean_position = position) %>% 
  mutate(clean_position = case_when(
  clean_position == "G" ~ "Guard", 
  clean_position == "F" ~ "Forward",
  TRUE ~ clean_position
  ))
```

```{r}
rosters23_clean <- rosters23_clean %>% filter(is.na(high_school))
```

```{r}
rosters23_clean <- rosters23_clean %>% mutate(
  height = str_replace(height, '-', "'")
)

rosters23_clean <- rosters23_clean %>% separate(col=height, into=c("height_ft", "height_in"), sep="'", extra="merge")
rosters23_clean <- rosters23_clean %>% mutate(height_in = str_replace(height_in, '"', " "))
rosters23_clean$height <- paste(rosters23_clean$height_ft, "-", rosters23_clean$height_in)
```

